In [1]:
# 1. First we will study what really Data Science is:
# Data Science involve steps like: i.Define Problem, ii.Data Collection, iii.EDA, iv.Data Cleaning, 
# v.Feature Engineering, vi.Modeling, vii.Evaluation, viii.Deployment

In [2]:
# 2. EDA: is the process of exploring data, means Data examine, summarizing, visualizing data and from that we find
# some patterns, problems in data, main characteristics and form of ideas.

# EDA contain following steps: 
# i.Load Data & structure, ii.Clean Data, iii.Statistical summary(mean, median etc), iv. visualization of data.
# we used Panda library for these steps specially for first 3 steps, and also we can do basic visualization using Panda but 
# Matplotlib and Seaborn Libraries are used for Visualization

In [10]:
# 3. Pandas Started. we use Pandas to play with data. we use NumPy for numerical computation (provide ndarray DS) but 
# Pandas are are mainly used for Data manipulation and Provide Data Structure like. Dataframe, and Series 
# 1. Series: 1D labelled array     2. Dataframe: 2D labelled array
import pandas as pd

# Convert Python Dictionary to Pandas DataFrame
info = {
    "name" : ["Ali", "Haroon", "Khan"],
    "CGPA" : [3.33, 3.22, 4.0]
}

df = pd.DataFrame(info)
print(df)
print("\n\nProper Table form is")
df

     name  CGPA
0     Ali  3.33
1  Haroon  3.22
2    Khan  4.00


Proper Table form is

     name  CGPA
0     Ali  3.33
1  Haroon  3.22
2    Khan  4.00

In [20]:
# 4. Series: 1D labelled array. it is also homogenous means same type of data are stored  
s = pd.Series([23,24,25,26], index = ["Ali", "Harry", "Khan", "Jhon"]) # here index = [] used to labelled series data
# without index = [] by default 0,1,2,3,... labels are asign
print(s)
print(s["Ali"]) # acces value using label
print(s["Jhon"]) 
print(s[0]) # acces value using index
print(s.index) # Print Labels of series
print(type(s))

Ali      23
Harry    24
Khan     25
Jhon     26
dtype: int64
23
26
23
Index(['Ali', 'Harry', 'Khan', 'Jhon'], dtype='object')
<class 'pandas.core.series.Series'>

C:\Users\Mr Laptop\AppData\Local\Temp\ipykernel_12020\464949626.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0]) # acces value using index

In [26]:
# 5. Properties of Serires: i.Homogenous, ii.Vectorized operation, iii.Handle missing values with NaN, 
    # iv.Mutable values but immutable size
# i.Homogenous example
s = pd.Series([23,24,25,26, "abc"], index = ["Ali", "Harry", "Khan", "Jhon", 23])
print(s)
print(type(s))

# ii. Vectorized operation eg.
s1 = pd.Series([1,3,4,5,6])
s2 = pd.Series([11,33,44,55,66])
s3 = s1*3
print(s3)
print(s1 + s2)

# iv. Mutable Values
s1[0] = 40
print(s1)

# iv. Immutable size if we change, that create new series changes happen there original series remain same e.g.
changed_s1 = s1.drop(0) # this drop remove index
print(s1)
print(changed_s1)

Ali       23
Harry     24
Khan      25
Jhon      26
23       abc
dtype: object
<class 'pandas.core.series.Series'>
0     3
1     9
2    12
3    15
4    18
dtype: int64
0    12
1    36
2    48
3    60
4    72
dtype: int64
0    40
1     3
2     4
3     5
4     6
dtype: int64
0    40
1     3
2     4
3     5
4     6
dtype: int64
1    3
2    4
3    5
4    6
dtype: int64

In [35]:
# 6. DataFrame: we can create DataFrame from: i. Dictionary, ii.List of Lists, iii.Numpy array
# Diction eg:
info_dic = {
    "name" : ["Harry", "Eve", "Bob"],
    "age" : [23,44,53],
    "CGPA" : [4.3, 2.3, 3.44]
}

df = pd.DataFrame(info_dic)
print(df, "\n", type(df))
df
print(df.index) # print horizental rows
print(df.columns) # print columns name

# List of Lists e.g:
df = pd.DataFrame([["Bob", 33], ["Jhon", 44], ["Eve", 30]], columns = ["name", "age"])
df

# Numpy array e.g:
import numpy as np
arr = np.array([[1, 23, 4], [3, 44, 5], [12, 33, 44]])
df = pd.DataFrame(arr, columns = ["A", "B", "C"])
df

    name  age  CGPA
0  Harry   23  4.30
1    Eve   44  2.30
2    Bob   53  3.44
 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'CGPA'], dtype='object')

    A   B   C
0   1  23   4
1   3  44   5
2  12  33  44

In [36]:
# 7. CSV Data 
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [40]:
# Json formate
df = pd.read_json("employee_data.json")
print(df, type(df))

   id     name  age department  salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [52]:
# Methods 
df.head() # starting 5 rows
df.tail() # last 5 rows
df.tail(2) # last 2 rows
df.sample() # any random row
df.sample(5) # any 5 random rows
df.info() # give summary of the data or any information
df.shape # return a tuple of the row and column value
df.describe() #it gives some information about data like mean, max, min etc
df.columns # print all columns vlaue
df.nunique() # gives unique value about rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          10 non-null     int64
 1   name        10 non-null     object
 2   age         10 non-null     int64
 3   department  10 non-null     object
 4   salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

id            10
name          10
age           10
department     4
salary        10
dtype: int64

In [61]:
# AQI Data Set
df = pd.read_csv("globalAirQuality.csv")
#df.head(10)
#df.tail()
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [80]:
# Selecting Data
# Column wise data access
df["country"]
df[["city", "aqi"]]

# for rows
# Select rows: for rows we use i.loc for labels and ii.iloc for indexes 
df.loc[0] # first row data 
df.loc[0:3] # here we use slice format from row 0 to 3: loc[starting : ending ] also ending index included (inlusive)

df.iloc[2] # here index 2 will be printed
df.iloc[0:2] # In indexing the ending value in exclusive not included
# print row and column using loc and iloc
df.loc[0, "aqi"]
df.loc[0,["city", "aqi"]]
df.loc[0:2,["city", "aqi"]]

#df.iloc[0:2, "aqi"] # this will cause and error as iloc don't accept string as it work with indexes so only numerics are allow for this first we will print index
df.columns # this will print columns and there we will count name of column and will be selected
df.iloc[0:2, 2]
df.iloc[0:2, 1:5]

# cell: we use at for labels and iat for index
df.at[0, "city"] # 0 shows row and city is the label
df.iat[0, 2] # here 0 shows row and 2 shows index of city

# * one thing important that we get view only not copy of that.
# so we do mistake that we replace the data by mistake. so if we need to change something firs make copy using copy() function at last connect with dot(.)
# so that we make safe room. then we change
# e.g.
cities = df["city"].copy()
cities[0] = "Mumbai" # here copy is updated
cities

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [88]:
# Filtering of Data 
# 1.using [] indxeing or labels
df[df["aqi"] > 100]

df[(df["aqi"] > 100) & (df["temperature"] > 30)]

# here done chaining along with filtering
df[df["aqi"] > 100 ] [["city",  "aqi"]]

# Query method return copy not view
# 2.Using query() . Rules: we write condintion in string, using column name , backticks for col_name with space or sepcial chars, operators are same and also refrence to python variable, and Chained comparision
df.query("aqi > 100")
df.query("aqi > 100 & temperature >30")

# also we can do chaining where only needed column can be filtered
df.query("aqi > 100 & temperature >30")[["city", "aqi"]]
df.query("aqi > 100 & temperature >30")[["city", "aqi"]]

aqi_val = 100
df.query("aqi > @aqi_val & temperature >30")[["city", "aqi"]] # python refrence variable

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [104]:
# CLeaning Data
df = pd.read_csv("raw_data.csv")
df
# 1. Handle missing Values
df.isnull() # it return True if any null or missing value found
df.isna() # it is the alias(second name or same function) of isnull() 
df.isnull().sum() # this is chaining like it tell how many values are missing in any column 
df.dropna() # this will drop any row where any missing value occur
df.dropna(axis = 1) # this will drop column if any missing value occur. so only axis changed into column
df.fillna(0) # this will fill all missing values with value we passed here we passed 0

# to fill specific column with specific value and to seperate clean data 

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean) # this will fill only specific column we selected
cleaned_data

# ffill() : forward fill here wi move vertically and if any missing value occure in the upcomming cell we fill with 
# that value like in row 0 value 1 but row 1 is null we fill with row 0 value called 1
df.ffill()

# bfill() : it is just opposite of the ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [108]:
# Handle Duplicate values, so we deduplication to remove duplicate values
df.duplicated() # this will print True if any duplicated record found 
df["country"].duplicated() # only for one column
df[["country" , "gender"]].duplicated() # only for one column

df2 = df.copy()
df2.drop_duplicates(inplace = True) # inplace is used that values change oringinally not only change in view that is  why i made the copy also

In [123]:
# Handle Different Data Types & Date-time
# to check data type used dtypes function 
df.dtypes 
df2.dtypes
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64")
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [125]:
# DataTime conversion we use to_datatime()
date_str = pd.Series(["2026-12-31"])
type(date_str.dtypes) 

datetime = pd.Series([pd.to_datetime("2026-12-31")])
type(datetime.dtypes)

numpy.dtypes.DateTime64DType

In [134]:
# Handle Strings 
df["gender"].str.lower() # convert into lower vlaues
df["gender"].str.upper() # convert into upper values
df["gender"].str.capitalize() # convert first letter inot upper case
df["gender"].str.strip() # used to remvoe extra spaces
df["name"].str.split(" ") # splite the name based on spaced also on anyother values like email: haroon@gmail.com here if split("@") so will divide haroon, gmail.com 
df["country"].str.contains("US") # checks is that US present in country column if present return True
df["country"].str.contains("india", case = False) # case = False is used to ignore case

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object